### ISSUE TITLE
感谢作者开源，请问有官方交流群没？

### ISSUE THREAD

**Issue by MaxMax2016** [netease-youdao/EmotiVoice#1]

**Comment by netease-youdao** [comment]
已更新在README中。

谢谢关注

**Comment by syq163** [comment]
![3841699671389_ pic](https://github.com/netease-youdao/EmotiVoice/assets/6308304/4be01b5c-5208-4dde-99de-ea1ed5d0a573)
You can also scan this QR code to join the WeChat communication group (before November 18th).

**Comment by fengcheche** [comment]
群可以拉我一下吗，申请不进去
