### ISSUE TITLE
训练模型，怎么把已有的英语数据转换为易魔声需要的格式

### ISSUE THREAD

**Issue by songyinghao** [netease-youdao/EmotiVoice#102]
**prosody数据如下：**
`100028_S0000	yes#1 they#1 are#3 i#1 like#3 them#4`
`
	Y1 EH1 S1 / DH1 / EY1 ER1 / AY1 / L1 AY1 K1 / DH1 AH1 M1`

**EmotiVoice需要的格式如下**
`"text":["<sos/eos>"] + phones+ ["<sos/eos>"],`

请问该怎么拼接phones呢

**Comment by syq163** [comment]
Are you asking about the data format for training or inference purposes?

**Comment by songyinghao** [comment]
@syq163 对不起，我描述的不清楚。
1，场景：
根据英文语料，训练TTS

2，训练数据情况（已经有prosody(phones)，无需自动生成）
![image](https://github.com/netease-youdao/EmotiVoice/assets/2515932/2afc5d54-6ecd-4e4f-b0ab-5c9df69be1d6)
![image](https://github.com/netease-youdao/EmotiVoice/assets/2515932/9115a7e8-7a41-44b0-91d2-352f9b3461a8)


3，EmotiVoice提供的训练的示例代码
![image](https://github.com/netease-youdao/EmotiVoice/assets/2515932/347279da-8421-49d3-b289-60bc04b410ff)

**问题：**
请问上面的第三点，请问怎么把训练数据中的phones转成EmotiVoice需要的格式呢

训练数据：
`100010_S0000	it#3's#1 cheap#4`
	`IH1 T1 S1 / S1 IY1 EY1 CH1 IY1 AH1 P1 IY1`

**Comment by songyinghao** [comment]
已解决，使用EmotiVoice自带的FrontEnd生成数据
