### ISSUE TITLE
推理时，生成的音频最后一个字或者最后一个音几乎听不到

### ISSUE THREAD

**Issue by Lili-q** [netease-youdao/EmotiVoice#141]
使用预训练模型推理时，无论是中文句子还是英文句子，最后一个字或者最后一个音几乎听不到，感觉像是被吞掉了，请问是怎么回事，怎么解决呢？

**Comment by lithStudy** [comment]
> 使用预训练模型推理时，无论是中文句子还是英文句子，最后一个字或者最后一个音几乎听不到，感觉像是被吞掉了，请问是怎么回事，怎么解决呢？

请问您的问题是怎么解决的？我也遇到了这个问题，并且最后加标点符号或者空格都没有用
