### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by King-Chau** [netease-youdao/EmotiVoice#18]
![75A0B5A2A3349E41D8EA3051EDF8CB38](https://github.com/netease-youdao/EmotiVoice/assets/7876435/f5c4eb52-fc75-4be0-b22b-016b240cca13)

text:
一枚天鹅蛋在鸭窠里被母鸭孵出后，它长相奇丑无比。被同行，外行甚至养殖场的歧视，嘲笑它是丑小鸭。经历过无数风霜的丑小鸭安全地长大了，眼尖的天师傅发现了它。于是乎和老板约定以6元一斤收购了。很快，丑小鸭被做成一直美味的烤天鹅。

**Comment by KimigaiiWuyi** [comment]
#17

**Comment by syq163** [comment]
The issue you mentioned will be addressed and resolved in the upcoming version 0.2.

**Comment by syq163** [comment]
The issue has been resolved. Please update to confirm.
