### ISSUE TITLE
The pretrained models？

### ISSUE THREAD

**Issue by HeJinLing** [netease-youdao/EmotiVoice#21]
The pretrained models cannot be downloaded， is there another link?

**Comment by syq163** [comment]
There are two pretrained models available. The first one can be found at https://huggingface.co/WangZeJun/simbert-base-chinese, while the second one is located in the [pretrained models](https://drive.google.com/drive/folders/1y6Xwj_GG9ulsAonca_unSGbJ4lxbNymM?usp=sharing) folder. Could you please clarify which one you are referring to?

**Comment by HeJinLing** [comment]
I'm referring to the second hyperlink cannot be opened, 'the pretrained models' folder.

**Comment by syq163** [comment]
Sure, we can attempt to upload it to another platform, such as Hugging Face.

**Comment by syq163** [comment]
Please try the following command to download the pretrained model:
 git clone https://www.modelscope.cn/syq163/outputs.git
