### ISSUE TITLE
style_prompt不起作用

### ISSUE THREAD

**Issue by Anker-ZX-AI** [netease-youdao/EmotiVoice#26]
Maria_Kasper|哭唧唧|<sos/eos>  uo3 sp1 l ai2 sp0 d ao4 sp1 b ei3 sp0 j ing1 sp3 q ing1 sp0 h ua2 sp0 d a4 sp0 x ve2 <sos/eos>|我来到北京，清华大学
Maria_Kasper|非常开心|<sos/eos>  uo3 sp1 l ai2 sp0 d ao4 sp1 b ei3 sp0 j ing1 sp3 q ing1 sp0 h ua2 sp0 d a4 sp0 x ve2 <sos/eos>|我来到北京，清华大学
上面两种inference text一个来自readme样例，一个来自data/inference/text，生成的音频听不出区别，另外三种语速也感受不到实际差别，只是style_embedding确实不同，但实际效果几乎没有差别

**Comment by zf3** [comment]
Duplicate of #29
