### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'seek'. 

### ISSUE THREAD

**Issue by henji-henji** [netease-youdao/EmotiVoice#27]
I tried to run the program in Windows 10 and the web page opens with an error
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
![Snipaste_2023-11-15_17-20-30](https://github.com/netease-youdao/EmotiVoice/assets/84775360/d92bcf38-8294-410e-9479-328f6641736e)

**Comment by syq163** [comment]
This issue may be attributed to a lack of model files.

**Comment by henji-henji** [comment]
> This issue may be attributed to a lack of model files.
I should have downloaded all the models I need. These are the ones, right?
![model01](https://github.com/netease-youdao/EmotiVoice/assets/84775360/4d1bfd07-2184-465f-b727-e9435850efee)
![model02](https://github.com/netease-youdao/EmotiVoice/assets/84775360/d1d2b81d-6549-4795-8094-6bb0436eb4cc)

**Comment by henji-henji** [comment]
> This issue may be attributed to a lack of model files.

I should have downloaded all the models I need. These are the ones, right?
![model01](https://github.com/netease-youdao/EmotiVoice/assets/84775360/5999774e-ad9d-4c28-9c5f-f14cdb5ab8cb)
![model02](https://github.com/netease-youdao/EmotiVoice/assets/84775360/634c6b4b-acc3-4822-8784-1f7774846276)

**Comment by fayaz07** [comment]
Hey @henji-henji , where do we get the do_*, checkpiont_* files?

**Comment by henji-henji** [comment]
> Hey @henji-henji , where do we get the do__, checkpiont__ files?

You can download these files from here, as mentioned in the README
https://drive.google.com/drive/folders/1y6Xwj_GG9ulsAonca_unSGbJ4lxbNymM?usp=sharing

**Comment by fayaz07** [comment]
Thanks @henji-henji

**Comment by xinmos** [comment]
> > This issue may be attributed to a lack of model files.
> 
> I should have downloaded all the models I need. These are the ones, right? ![model01](https://user-images.githubusercontent.com/84775360/283090647-5999774e-ad9d-4c28-9c5f-f14cdb5ab8cb.jpg) ![model02](https://user-images.githubusercontent.com/84775360/283090668-634c6b4b-acc3-4822-8784-1f7774846276.jpg)

Maybe you can try deleting the file extension ‘.zip’.

**Comment by henji-henji** [comment]
I tried it and it works, thank you! @xinmos
