### ISSUE TITLE
encode error when open file

### ISSUE THREAD

**Issue by xinmos** [netease-youdao/EmotiVoice#33]
When starting with 'streamlit run demo_page.py', you may encounter the following error: **"UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2: illegal multibyte sequence".**

To resolve this issue, it is recommended to change the encoding when opening the file. You can do this by modifying your code as follows:
the file path: EmotiVoice/config/joint/config.py
```
#### Speaker ####
with open(speaker2id_path, encoding='utf-8') as f:
    speakers = [t.strip() for t in f.readlines()]
speaker_n_labels = len(speakers)
```
![image](https://github.com/netease-youdao/EmotiVoice/assets/44024240/ef2276a3-8405-4c64-8cfb-7eb7f7bafaa4)

**Comment by fengcheche** [comment]
我也遇到这个问题了，改了不起作用呢

**Comment by fengcheche** [comment]
好像可以了

**Comment by Javed-ahmed-shanto** [comment]
I think you can find solution here: []((https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult))

**Comment by syq163** [comment]
The bug has already been fixed. Please update and give it a try.
