### ISSUE TITLE
请问能否提供一个可以在 gitee.com 或 国内主流云盘的下载地址？

### ISSUE THREAD

**Issue by auendx** [netease-youdao/EmotiVoice#4]
目前 https://huggingface.co 好像国内很难访问，请支持一下国内开发者和测试者，提供一个方便国内网络下载本项目模型或较大文件的地址。谢谢先。

**Comment by syq163** [comment]
Yes, accessing huggingface.co is challenging in China, and we are actively looking for an alternative solution.

**Comment by syq163** [comment]
Please try the following command to download the simbert-base-chinese model:
`git clone https://www.modelscope.cn/syq163/WangZeJun.git`
