### ISSUE TITLE
建议增加一个http类的接口方便集成到运营环境中，开箱即用

### ISSUE THREAD

**Issue by snamper** [netease-youdao/EmotiVoice#42]
建议使用 get或者post 传文字 、speaker_id 、提示这类参数    返回文件 url  或者音频数据

如果为了效率可以增加一层缓存 ，对 传参做个md5，作为文件名    缓存文件效果也挺好

**Comment by syq163** [comment]
Great idea! We will consider it as soon as possible, for example by providing a dedicated API service through ai.youdao.com.
