### ISSUE TITLE
How to obtain the pretrained model

### ISSUE THREAD

**Issue by lucasjinreal** [netease-youdao/EmotiVoice#5]
How to obtain the pretrained model

**Comment by syq163** [comment]
Two methods:
1. Utilize the EmotiVoice Docker image directly.
2. Follow the instructions in the "Prepare model files" section and download the [pretrained models](https://drive.google.com/drive/folders/1y6Xwj_GG9ulsAonca_unSGbJ4lxbNymM?usp=sharing) from Google Drive.
Hope that helps.
