### ISSUE TITLE
Inserting pause is not working

### ISSUE THREAD

**Issue by PatroxGaurab** [netease-youdao/EmotiVoice#59]
tried with `<break>` with ... everything but it does not insert a pause. Did anyone else face the same issue?

**Comment by syq163** [comment]
I updated the Docker image 10 minutes ago. You can update it by running `docker pull syq163/emoti-voice:latest` , then rerun it using `docker run -dp 127.0.0.1:8501:8501 syq163/emoti-voice:latest`.

**Comment by PatroxGaurab** [comment]
Changed the necessary things and working fine, closing the issue. Thanks a lot @syq163
