### ISSUE TITLE
哪里可以看全部的speaker ?

### ISSUE THREAD

**Issue by makao007** [netease-youdao/EmotiVoice#7]
我的 data/inference/text 看到样例文件，每行的前面部分是指定speaker,那么如何查看全部可用的speaker呢？
这12个speaker就已经是全部的speaker ?

**Comment by makao007** [comment]
看到 data/youdao/text/speaker2 文件里面有一个列表，就是这个吗？

**Comment by syq163** [comment]
Sure, you can find it in the data/youdao/text/speaker2 directory, and we will provide a wiki page with additional information for your reference.

**Comment by bank010** [comment]
> Sure, you can find it in the data/youdao/text/speaker2 directory, and we will provide a wiki page with additional information for your reference.

期待

**Comment by King-Chau** [comment]
建议加一下每个speak的音色描述

**Comment by makao007** [comment]
加个简单明了的speaker中文名称就好了。

**Comment by mdsxbm** [comment]
现在这音色跟开盲盒一样

**Comment by syq163** [comment]
The 'Voice Wiki Page' has already been added. Please take a look at:
https://github.com/netease-youdao/EmotiVoice/tree/main/data/youdao/text
https://github.com/netease-youdao/EmotiVoice/wiki/%F0%9F%98%8A-voice-wiki-page
