### ISSUE TITLE
http api

### ISSUE THREAD

**Issue by shenyw0103** [netease-youdao/EmotiVoice#70]
文档中的http api是云端的接口，请问私有化部署后是否有http api？

**Comment by shenyw0103** [comment]
已解决，感谢开源

**Comment by shenyw0103** [comment]
已解决，感谢开源

**Comment by zsanjin-p** [comment]
> 文档中的http api是云端的接口，请问私有化部署后是否有http api？

所以有吗

**Comment by syq163** [comment]
Yes. Refer to 'Openai compatible API' in https://github.com/netease-youdao/EmotiVoice/releases/tag/v0.3 for details.
