### ISSUE TITLE
Problem with the last phoneme not sounding in some cases

### ISSUE THREAD

**Issue by clcarwin** [netease-youdao/EmotiVoice#71]
I have found that some word do not pronounce if it in the end of the sentence. Can we have a method to work around this problem?

```8051|Happy|[L] [AH1] [V] engsp1 [M] [IY1]|love me```
[output_loveme.zip](https://github.com/netease-youdao/EmotiVoice/files/13656801/output_loveme.zip)

```11614|Happy|[HH] [AH0] [L] [OW1] engsp4 [K] [AE1] [N] engsp1 [Y] [UW1] engsp1 [HH] [EH1] [L] [P] engsp1 [M] [IY1]|hello, can you help me?```
[output_hellocanyouhelpme.zip](https://github.com/netease-youdao/EmotiVoice/files/13656806/output_hellocanyouhelpme.zip)

```8051|Happy|[AY1] engsp1 [AE1] [M] engsp1 [B] [EH1] [S] [T] engsp4 [TH] [AE1] [NG] [K] engsp1 [Y] [UW1]|i am best, thank you.```
[output_iambestthankyou.zip](https://github.com/netease-youdao/EmotiVoice/files/13656810/output_iambestthankyou.zip)

**Comment by syq163** [comment]
I have confirmed this issue. It appears that the phonemes are not accurate. Could you please explain how you generated the phonemes?

**Comment by clcarwin** [comment]
Following the instructions in README.md, the phonemes have been generated by ```python frontend_en.py data/my_text.txt > data/my_text_for_tts.txt```

**Comment by syq163** [comment]
> Following the instructions in README.md, the phonemes have been generated by `python frontend_en.py data/my_text.txt > data/my_text_for_tts.txt`

The issue has been identified and the code has been updated! Please make sure to update the code and check if it is functioning properly now. The problem was caused by the missing "sos/eos" in the phonemes.

**Comment by clcarwin** [comment]
It works now. Thanks.
