### ISSUE TITLE
Can you Highlight the prompttts code

### ISSUE THREAD

**Issue by francqz31** [netease-youdao/EmotiVoice#73]
Hello Author, 

I just wanted you to point out the pure prompttts code for me, as i wanted to develop some stuff upon it.

Also I'm wondering if you implemented the prompttts paper correctly and didn't miss anything in it.

Thanks in advance!

**Comment by syq163** [comment]
I recommend that you review the code located in models/prompt_tts_modified, including files such as prompt_dataset.py and others.
