### ISSUE TITLE
增加的openaiapi.py怎么用，我是用docker直接运行的，想用api不清楚端口是哪个，求解

### ISSUE THREAD

**Issue by zsanjin-p** [netease-youdao/EmotiVoice#87]
看到 #60 增加api功能，目前我用docker部署的，目前只知道8501端口，但是api的端口不清楚，问一下怎么弄

**Comment by zsanjin-p** [comment]
post这个路径后/v1/audio/speech返回的是403，不知道是不是有设置默认的apikey？还是什么原因吗

**Comment by syq163** [comment]
Before attempting to use 'v1/audio/speech', please follow the steps outlined in the 'OpenAI-compatible-TTS API' section. Note that 'apikey' is not necessary for this, but it is required if you intend to use '[The EmotiVoice HTTP API](https://github.com/netease-youdao/EmotiVoice/wiki/HTTP-API)'.

**Comment by zsanjin-p** [comment]
> OpenAI



> Before attempting to use 'v1/audio/speech', please follow the steps outlined in the 'OpenAI-compatible-TTS API' section. Note that 'apikey' is not necessary for this, but it is required if you intend to use '[The EmotiVoice HTTP API](https://github.com/netease-youdao/EmotiVoice/wiki/HTTP-API)'.

So it means that the Docker installation method cannot be used for APIs, and an API service must be installed and run in a Python environment in order to use the API, right?

**Comment by syq163** [comment]
Yes, currently Docker is primarily intended for experiencing the demo page, but we can also include the 'OpenAI-compatible-TTS API' in the Docker image.

**Comment by lonngxiang** [comment]
> Yes, currently Docker is primarily intended for experiencing the demo page, but we can also include the 'OpenAI-compatible-TTS API' in the Docker image.

how to use OpenAI-compatible-TTS API?

**Comment by xushilundao** [comment]
解析配置文件这个逻辑是代码处理的，所以如果不知道后台对配置文件的处理，我们根本不知道key是该配还是不该配。所以还请作者如果不想开源代码，给出详细的文档解释或者打出日志供调试，而不是一句”你需要有网络开放经验“，一句糊弄过去。
